// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: core.proto

package core

import (
	"context"

	"github.com/Yooz-1999/agentforge/apps/core-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Agent                           = pb.Agent
	AgentResponse                   = pb.AgentResponse
	BuildChatContextRequest         = pb.BuildChatContextRequest
	BuildChatContextResponse        = pb.BuildChatContextResponse
	Conversation                    = pb.Conversation
	ConversationResponse            = pb.ConversationResponse
	CreateAgentRequest              = pb.CreateAgentRequest
	CreateAssistantMessageRequest   = pb.CreateAssistantMessageRequest
	CreateConversationRequest       = pb.CreateConversationRequest
	CreateUserMessageRequest        = pb.CreateUserMessageRequest
	DeleteAgentRequest              = pb.DeleteAgentRequest
	Empty                           = pb.Empty
	GetAgentRequest                 = pb.GetAgentRequest
	GetConversationMessagesRequest  = pb.GetConversationMessagesRequest
	GetConversationMessagesResponse = pb.GetConversationMessagesResponse
	GetUserForAuthRequest           = pb.GetUserForAuthRequest
	GetUserForAuthResponse          = pb.GetUserForAuthResponse
	ListAgentsRequest               = pb.ListAgentsRequest
	ListAgentsResponse              = pb.ListAgentsResponse
	ListConversationsRequest        = pb.ListConversationsRequest
	ListConversationsResponse       = pb.ListConversationsResponse
	Message                         = pb.Message
	MessageResponse                 = pb.MessageResponse
	RegisterUserRequest             = pb.RegisterUserRequest
	RegisterUserResponse            = pb.RegisterUserResponse
	UpdateAgentRequest              = pb.UpdateAgentRequest
	User                            = pb.User
	VerifyLoginRequest              = pb.VerifyLoginRequest
	VerifyLoginResponse             = pb.VerifyLoginResponse

	Core interface {
		RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
		VerifyLogin(ctx context.Context, in *VerifyLoginRequest, opts ...grpc.CallOption) (*VerifyLoginResponse, error)
		GetUserForAuth(ctx context.Context, in *GetUserForAuthRequest, opts ...grpc.CallOption) (*GetUserForAuthResponse, error)
		CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error)
		UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error)
		DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*Empty, error)
		GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error)
		ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
		CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*ConversationResponse, error)
		ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
		GetConversationMessages(ctx context.Context, in *GetConversationMessagesRequest, opts ...grpc.CallOption) (*GetConversationMessagesResponse, error)
		CreateUserMessage(ctx context.Context, in *CreateUserMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
		CreateAssistantMessage(ctx context.Context, in *CreateAssistantMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
		BuildChatContext(ctx context.Context, in *BuildChatContextRequest, opts ...grpc.CallOption) (*BuildChatContextResponse, error)
	}

	defaultCore struct {
		cli zrpc.Client
	}
)

func NewCore(cli zrpc.Client) Core {
	return &defaultCore{
		cli: cli,
	}
}

func (m *defaultCore) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.RegisterUser(ctx, in, opts...)
}

func (m *defaultCore) VerifyLogin(ctx context.Context, in *VerifyLoginRequest, opts ...grpc.CallOption) (*VerifyLoginResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.VerifyLogin(ctx, in, opts...)
}

func (m *defaultCore) GetUserForAuth(ctx context.Context, in *GetUserForAuthRequest, opts ...grpc.CallOption) (*GetUserForAuthResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.GetUserForAuth(ctx, in, opts...)
}

func (m *defaultCore) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.CreateAgent(ctx, in, opts...)
}

func (m *defaultCore) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.UpdateAgent(ctx, in, opts...)
}

func (m *defaultCore) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.DeleteAgent(ctx, in, opts...)
}

func (m *defaultCore) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.GetAgent(ctx, in, opts...)
}

func (m *defaultCore) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.ListAgents(ctx, in, opts...)
}

func (m *defaultCore) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*ConversationResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.CreateConversation(ctx, in, opts...)
}

func (m *defaultCore) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.ListConversations(ctx, in, opts...)
}

func (m *defaultCore) GetConversationMessages(ctx context.Context, in *GetConversationMessagesRequest, opts ...grpc.CallOption) (*GetConversationMessagesResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.GetConversationMessages(ctx, in, opts...)
}

func (m *defaultCore) CreateUserMessage(ctx context.Context, in *CreateUserMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.CreateUserMessage(ctx, in, opts...)
}

func (m *defaultCore) CreateAssistantMessage(ctx context.Context, in *CreateAssistantMessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.CreateAssistantMessage(ctx, in, opts...)
}

func (m *defaultCore) BuildChatContext(ctx context.Context, in *BuildChatContextRequest, opts ...grpc.CallOption) (*BuildChatContextResponse, error) {
	client := pb.NewCoreClient(m.cli.Conn())
	return client.BuildChatContext(ctx, in, opts...)
}
