// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/Yooz-1999/agentforge/apps/chat-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/chat/stream",
					Handler: ChatStreamHandler(serverCtx),
				},
			}...,
		),
	)
}
