// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AgentItem struct {
	Id            int64   `json:"id"`
	Name          string  `json:"name"`
	Description   string  `json:"description"`
	SystemPrompt  string  `json:"system_prompt"`
	ModelProvider string  `json:"model_provider"`
	ModelName     string  `json:"model_name"`
	Temperature   float64 `json:"temperature"`
	MaxTokens     int64   `json:"max_tokens"`
	Status        int64   `json:"status"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
}

type AgentResponse struct {
	Agent AgentItem `json:"agent"`
}

type ConversationItem struct {
	Id            int64  `json:"id"`
	AgentId       int64  `json:"agent_id"`
	Title         string `json:"title"`
	Status        int64  `json:"status"`
	LastMessageAt string `json:"last_message_at"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type ConversationResponse struct {
	Conversation ConversationItem `json:"conversation"`
}

type CreateAgentRequest struct {
	Name          string  `json:"name"`
	Description   string  `json:"description"`
	SystemPrompt  string  `json:"system_prompt"`
	ModelProvider string  `json:"model_provider"`
	ModelName     string  `json:"model_name"`
	Temperature   float64 `json:"temperature"`
	MaxTokens     int64   `json:"max_tokens,optional"`
}

type CreateConversationRequest struct {
	AgentId int64  `json:"agent_id"`
	Title   string `json:"title,optional"`
}

type DeleteAgentRequest struct {
	Id int64 `path:"id"`
}

type EmptyResponse struct {
}

type GetAgentRequest struct {
	Id int64 `path:"id"`
}

type ListAgentsResponse struct {
	List []AgentItem `json:"list"`
}

type ListConversationsRequest struct {
	AgentId int64 `form:"agent_id,optional"`
	Page    int64 `form:"page,optional"`
	Size    int64 `form:"size,optional"`
}

type ListConversationsResponse struct {
	List []ConversationItem `json:"list"`
}

type ListMessagesRequest struct {
	Id int64 `path:"id"`
}

type ListMessagesResponse struct {
	List []MessageItem `json:"list"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string   `json:"access_token"`
	RefreshToken string   `json:"refresh_token"`
	ExpiresIn    int64    `json:"expires_in"`
	User         UserInfo `json:"user"`
}

type MessageItem struct {
	Id               int64  `json:"id"`
	ConversationId   int64  `json:"conversation_id"`
	Role             string `json:"role"`
	Content          string `json:"content"`
	ModelProvider    string `json:"model_provider,optional"`
	ModelName        string `json:"model_name,optional"`
	Status           int64  `json:"status"`
	ErrorMessage     string `json:"error_message,optional"`
	PromptTokens     int64  `json:"prompt_tokens,optional"`
	CompletionTokens int64  `json:"completion_tokens,optional"`
	CreatedAt        string `json:"created_at"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type RegisterResponse struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
}

type UpdateAgentRequest struct {
	Id            int64   `path:"id"`
	Name          string  `json:"name"`
	Description   string  `json:"description"`
	SystemPrompt  string  `json:"system_prompt"`
	ModelProvider string  `json:"model_provider"`
	ModelName     string  `json:"model_name"`
	Temperature   float64 `json:"temperature"`
	MaxTokens     int64   `json:"max_tokens,optional"`
	Status        int64   `json:"status"`
}

type UserInfo struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
}
