// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ChatStreamBootstrapResponse struct {
	RequestId string `json:"request_id"`
}

type ChatStreamRequest struct {
	AgentId        int64  `json:"agent_id"`
	ConversationId int64  `json:"conversation_id,optional"`
	Message        string `json:"message"`
}
