// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/Yooz-1999/agentforge/apps/gateway-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/refresh",
				Handler: RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/agents",
					Handler: ListAgentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/agents",
					Handler: CreateAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/agents/:id",
					Handler: GetAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/api/v1/agents/:id",
					Handler: UpdateAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/v1/agents/:id",
					Handler: DeleteAgentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/conversations",
					Handler: ListConversationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/v1/conversations",
					Handler: CreateConversationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/v1/conversations/:id/messages",
					Handler: ListMessagesHandler(serverCtx),
				},
			}...,
		),
	)
}
