// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: core.proto

package server

import (
	"context"

	"github.com/Yooz-1999/agentforge/apps/core-rpc/internal/logic"
	"github.com/Yooz-1999/agentforge/apps/core-rpc/internal/svc"
	"github.com/Yooz-1999/agentforge/apps/core-rpc/pb"
)

type CoreServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCoreServer
}

func NewCoreServer(svcCtx *svc.ServiceContext) *CoreServer {
	return &CoreServer{
		svcCtx: svcCtx,
	}
}

func (s *CoreServer) RegisterUser(ctx context.Context, in *pb.RegisterUserRequest) (*pb.RegisterUserResponse, error) {
	l := logic.NewRegisterUserLogic(ctx, s.svcCtx)
	return l.RegisterUser(in)
}

func (s *CoreServer) VerifyLogin(ctx context.Context, in *pb.VerifyLoginRequest) (*pb.VerifyLoginResponse, error) {
	l := logic.NewVerifyLoginLogic(ctx, s.svcCtx)
	return l.VerifyLogin(in)
}

func (s *CoreServer) CreateAgent(ctx context.Context, in *pb.CreateAgentRequest) (*pb.AgentResponse, error) {
	l := logic.NewCreateAgentLogic(ctx, s.svcCtx)
	return l.CreateAgent(in)
}

func (s *CoreServer) UpdateAgent(ctx context.Context, in *pb.UpdateAgentRequest) (*pb.AgentResponse, error) {
	l := logic.NewUpdateAgentLogic(ctx, s.svcCtx)
	return l.UpdateAgent(in)
}

func (s *CoreServer) DeleteAgent(ctx context.Context, in *pb.DeleteAgentRequest) (*pb.Empty, error) {
	l := logic.NewDeleteAgentLogic(ctx, s.svcCtx)
	return l.DeleteAgent(in)
}

func (s *CoreServer) GetAgent(ctx context.Context, in *pb.GetAgentRequest) (*pb.AgentResponse, error) {
	l := logic.NewGetAgentLogic(ctx, s.svcCtx)
	return l.GetAgent(in)
}

func (s *CoreServer) ListAgents(ctx context.Context, in *pb.ListAgentsRequest) (*pb.ListAgentsResponse, error) {
	l := logic.NewListAgentsLogic(ctx, s.svcCtx)
	return l.ListAgents(in)
}

func (s *CoreServer) CreateConversation(ctx context.Context, in *pb.CreateConversationRequest) (*pb.ConversationResponse, error) {
	l := logic.NewCreateConversationLogic(ctx, s.svcCtx)
	return l.CreateConversation(in)
}

func (s *CoreServer) ListConversations(ctx context.Context, in *pb.ListConversationsRequest) (*pb.ListConversationsResponse, error) {
	l := logic.NewListConversationsLogic(ctx, s.svcCtx)
	return l.ListConversations(in)
}

func (s *CoreServer) GetConversationMessages(ctx context.Context, in *pb.GetConversationMessagesRequest) (*pb.GetConversationMessagesResponse, error) {
	l := logic.NewGetConversationMessagesLogic(ctx, s.svcCtx)
	return l.GetConversationMessages(in)
}

func (s *CoreServer) CreateUserMessage(ctx context.Context, in *pb.CreateUserMessageRequest) (*pb.MessageResponse, error) {
	l := logic.NewCreateUserMessageLogic(ctx, s.svcCtx)
	return l.CreateUserMessage(in)
}

func (s *CoreServer) CreateAssistantMessage(ctx context.Context, in *pb.CreateAssistantMessageRequest) (*pb.MessageResponse, error) {
	l := logic.NewCreateAssistantMessageLogic(ctx, s.svcCtx)
	return l.CreateAssistantMessage(in)
}

func (s *CoreServer) BuildChatContext(ctx context.Context, in *pb.BuildChatContextRequest) (*pb.BuildChatContextResponse, error) {
	l := logic.NewBuildChatContextLogic(ctx, s.svcCtx)
	return l.BuildChatContext(in)
}
